In [20]:
#implementation of function "IterativeDFS"

import numpy as np
import time
goalstate = np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])
class NODEDFS:
    def __init__(self,data,parentnode,goalcost):
        self.data = data
        self.MOVEUP = None
        self.MOVELEFT = None
        self.MOVEDOWN = None
        self.MOVERIGHT = None
        self.parentnode = parentnode
        self.goalcost = goalcost
    
    def prob_MOVEUP(self):
        indexzero=np.where(self.data == 0)
        if indexzero[1] == 0:
            return False
        else:
            temp = self.data[indexzero[0],indexzero[1]-1]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0],indexzero[1]-1] = 0
            return newdata,True
       
    
    def prob_MOVELEFT(self):
        indexzero=np.where(self.data == 0)
        if indexzero[0] == 2:
            return False
        else:
            temp = self.data[indexzero[0]+1,indexzero[1]]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0]+1,indexzero[1]] = 0
            return newdata,True
        
        
    def prob_MOVEDOWN(self):
        indexzero=np.where(self.data == 0)
        if indexzero[1] == 2:
            return False
        else:
            temp = self.data[indexzero[0],indexzero[1]+1]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0],indexzero[1]+1] = 0
            return newdata,True
            
    def prob_MOVERIGHT(self):
        indexzero=np.where(self.data == 0)
        if indexzero[0] == 0:
            return False
        else:
            temp = self.data[indexzero[0]-1,indexzero[1]]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0]-1,indexzero[1]] = 0
            return newdata,True
        
    def IterativeDFS(self):
        iter_counter = 0
        for depth in range(100):
        
            queue = [self] 
            frontier = set([]) 
            cutoff = [0]
            goalqueue = [0]
            iter_counter += 1

            while queue:

                curr_node = queue.pop(0) 
                #print(curr_node.data)
                   
                curr_cutoff =cutoff.pop(0)
                tempgoal = goalqueue.pop(0)
                
                frontier.add(tuple(curr_node.data.reshape(1,9)[0]))

                if np.array_equal(curr_node.data,goalstate):
                    steps_count = curr_node.print_DFS()
                    return steps_count,iter_counter

                else:              
                    if curr_cutoff < depth:
                          
                        if curr_node.prob_MOVERIGHT():
                            newdata,garbage = curr_node.prob_MOVERIGHT()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVERIGHT = NODEDFS(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.insert(0,curr_node.MOVERIGHT)
                                cutoff.insert(0,curr_cutoff+1)
                                goalqueue.insert(0,goalcost)

                        if curr_node.prob_MOVEDOWN():
                            newdata,garbage = curr_node.prob_MOVEDOWN()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVEDOWN = NODEDFS(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.insert(0,curr_node.MOVEDOWN)
                                cutoff.insert(0,curr_cutoff+1)
                                goalqueue.insert(0,goalcost)

                        if curr_node.prob_MOVELEFT():
                            newdata,garbage = curr_node.prob_MOVELEFT()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVELEFT = NODEDFS(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.insert(0,curr_node.MOVELEFT)
                                cutoff.insert(0,curr_cutoff+1)
                                goalqueue.insert(0,goalcost)
                                
                                
                        if curr_node.prob_MOVEUP():
                            newdata,garbage = curr_node.prob_MOVEUP()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVEUP = NODEDFS(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.insert(0,curr_node.MOVEUP)
                                cutoff.insert(0,curr_cutoff+1)
                                goalqueue.insert(0,goalcost)
                                
    def print_DFS(self):
        trackdata = [self.data]
        goaltrack = [self.goalcost]
        
        while self.parentnode:
            self = self.parentnode
            trackdata.append(self.data)
            goaltrack.append(self.goalcost)
            
        print ('First Scenario Solution of the IterativeDFS:')
        while trackdata:
            print (trackdata.pop())
            print ('to') 
        return len(goaltrack)
    
    
    def iterdeepDFS_WOprint(self):
        iter_counter = 0
        for depth in range(100):
        
            queue = [self] 
            frontier = set([]) 
            cutoff = [0]
            goalqueue = [0]
            iter_counter += 1

            while queue:

                curr_node = queue.pop(0) 
                #print(curr_node.data)
                   
                curr_cutoff =cutoff.pop(0)
                tempgoal = goalqueue.pop(0)
                
                frontier.add(tuple(curr_node.data.reshape(1,9)[0]))

                if np.array_equal(curr_node.data,goalstate):
                    steps_count = curr_node.noresult_DFS()
                    return steps_count,iter_counter

                else:              
                    if curr_cutoff < depth:
                          
                        if curr_node.prob_MOVERIGHT():
                            newdata,garbage = curr_node.prob_MOVERIGHT()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVERIGHT = NODEDFS(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.insert(0,curr_node.MOVERIGHT)
                                cutoff.insert(0,curr_cutoff+1)
                                goalqueue.insert(0,goalcost)

                        if curr_node.prob_MOVEDOWN():
                            newdata,garbage = curr_node.prob_MOVEDOWN()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVEDOWN = NODEDFS(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.insert(0,curr_node.MOVEDOWN)
                                cutoff.insert(0,curr_cutoff+1)
                                goalqueue.insert(0,goalcost)
                               

                        if curr_node.prob_MOVELEFT():
                            newdata,garbage = curr_node.prob_MOVELEFT()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVELEFT = NODEDFS(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.insert(0,curr_node.MOVELEFT)
                                cutoff.insert(0,curr_cutoff+1)
                                goalqueue.insert(0,goalcost)
                                
                                
                        if curr_node.prob_MOVEUP():
                            newdata,garbage = curr_node.prob_MOVEUP()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVEUP = NODEDFS(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.insert(0,curr_node.MOVEUP)
                                cutoff.insert(0,curr_cutoff+1)
                                goalqueue.insert(0,goalcost)
                                
                                
    def noresult_DFS(self):
        goaltrack = [self.goalcost]
        
        while self.parentnode:
            self = self.parentnode
            goaltrack.append(self.goalcost)
            
        return len(goaltrack)


In [21]:
#implementation of function "AStarMisplaced"

import numpy as np
import time
goalstate = np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])
class AstarMisplacedNode:
    def __init__(self,data,parentnode,goalcost,heur_cost):
        self.data = data
        self.parentnode = parentnode
        self.goalcost = goalcost
        self.heur_cost = heur_cost
        self.MOVEUP = None
        self.MOVELEFT = None
        self.MOVEDOWN = None
        self.MOVERIGHT = None
    
    def prob_MOVEUP(self):
        indexzero=np.where(self.data == 0)
        if indexzero[1] == 0:
            return False
        else:
            temp = self.data[indexzero[0],indexzero[1]-1]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0],indexzero[1]-1] = 0
            return newdata,True
       
    
    def prob_MOVELEFT(self):
        indexzero=np.where(self.data == 0)
        if indexzero[0] == 2:
            return False
        else:
            temp = self.data[indexzero[0]+1,indexzero[1]]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0]+1,indexzero[1]] = 0
            return newdata,True
        
        
    def prob_MOVEDOWN(self):
        indexzero=np.where(self.data == 0)
        if indexzero[1] == 2:
            return False
        else:
            temp = self.data[indexzero[0],indexzero[1]+1]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0],indexzero[1]+1] = 0
            return newdata,True
            
    def prob_MOVERIGHT(self):
        indexzero=np.where(self.data == 0)
        if indexzero[0] == 0:
            return False
        else:
            temp = self.data[indexzero[0]-1,indexzero[1]]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0]-1,indexzero[1]] = 0
            return newdata,True
        
    def aStarMisplaced(self):
        
        queue = [(self,0)] 
        frontier = set([])
        goalqueue = [(0,0)]
        iter_counter = 0
            

        while queue:
                queue = sorted(queue, key=lambda x:x[1])
                curr_node = queue.pop(0)[0]
                goalqueue = sorted(goalqueue, key=lambda x:x[1])
                tempgoal = goalqueue.pop(0)[0]
                #print(curr_node.data)
                
                frontier.add(tuple(curr_node.data.reshape(1,9)[0]))
                iter_counter += 1
            
                if np.array_equal(curr_node.data,goalstate):
                    steps_count=curr_node.print_AstarMisplaced()
                    return steps_count,iter_counter

                else:              
                    if curr_node.prob_MOVERIGHT():
                        newdata,garbage = curr_node.prob_MOVERIGHT()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp_heurcost=np.sum(newdata!=goalstate)
                            total_cost = temp_heurcost + goalcost
                            curr_node.MOVERIGHT = AstarMisplacedNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVERIGHT,total_cost))
                            goalqueue.append((goalcost,total_cost))

                    if curr_node.prob_MOVEDOWN():
                        newdata,garbage = curr_node.prob_MOVEDOWN()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp_heurcost=np.sum(newdata!=goalstate)
                            total_cost = temp_heurcost + goalcost
                            curr_node.MOVEDOWN = AstarMisplacedNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVEDOWN,total_cost))
                            goalqueue.append((goalcost,total_cost))                               

                    if curr_node.prob_MOVELEFT():
                        newdata,garbage = curr_node.prob_MOVELEFT()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp_heurcost=np.sum(newdata!=goalstate)
                            total_cost = temp_heurcost + goalcost 
                            curr_node.MOVELEFT = AstarMisplacedNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVELEFT,total_cost))
                            goalqueue.append((goalcost,total_cost))
                                
                    if curr_node.prob_MOVEUP():
                        newdata,garbage = curr_node.prob_MOVEUP()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp_heurcost=np.sum(newdata!=goalstate)
                            total_cost = temp_heurcost + goalcost
                            curr_node.MOVEUP = AstarMisplacedNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVEUP,total_cost))
                            goalqueue.append((goalcost,total_cost))
                                
                                
    def print_AstarMisplaced(self):
        trackdata = [self.data]
        goaltrack = [self.goalcost]
        
        while self.parentnode:
            self = self.parentnode
            trackdata.append(self.data)
            
            goaltrack.append(self.goalcost)
        print ('First Scenario Solution of the Astar_misplaced:')
        
        while trackdata:
            print (trackdata.pop())
            #print(goaltrack.pop())
            print ('to') 
            
        return len(goaltrack)
    
    
    def astarMisplaced_WOprint(self):
        
        queue = [(self,0)] 
        frontier = set([])
        goalqueue = [(0,0)]
        iter_counter = 0
            

        while queue:
                queue = sorted(queue, key=lambda x:x[1])
                curr_node = queue.pop(0)[0]
                goalqueue = sorted(goalqueue, key=lambda x:x[1])
                tempgoal = goalqueue.pop(0)[0]
                #print(curr_node.data)
                
                frontier.add(tuple(curr_node.data.reshape(1,9)[0]))
                iter_counter += 1

                if np.array_equal(curr_node.data,goalstate):
                    steps_count=curr_node.noresult_AstarMisplaced()
                    return steps_count,iter_counter

                else:              
                    if curr_node.prob_MOVERIGHT():
                        newdata,garbage = curr_node.prob_MOVERIGHT()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp_heurcost=np.sum(newdata!=goalstate)
                            total_cost = temp_heurcost + goalcost
                            curr_node.MOVERIGHT = AstarMisplacedNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVERIGHT,total_cost))
                            goalqueue.append((goalcost,total_cost))

                    if curr_node.prob_MOVEDOWN():
                        newdata,garbage = curr_node.prob_MOVEDOWN()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp_heurcost=np.sum(newdata!=goalstate)
                            total_cost = temp_heurcost + goalcost
                            curr_node.MOVEDOWN = AstarMisplacedNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVEDOWN,total_cost))
                            goalqueue.append((goalcost,total_cost))                               

                    if curr_node.prob_MOVELEFT():
                        newdata,garbage = curr_node.prob_MOVELEFT()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp_heurcost=np.sum(newdata!=goalstate)
                            total_cost = temp_heurcost + goalcost 
                            curr_node.MOVELEFT = AstarMisplacedNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVELEFT,total_cost))
                            goalqueue.append((goalcost,total_cost))
                                
                    if curr_node.prob_MOVEUP():
                        newdata,garbage = curr_node.prob_MOVEUP()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp_heurcost=np.sum(newdata!=goalstate)
                            total_cost = temp_heurcost + goalcost
                            curr_node.MOVEUP = AstarMisplacedNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVEUP,total_cost))
                            goalqueue.append((goalcost,total_cost))
                                
                                
    def noresult_AstarMisplaced(self):
        goaltrack = [self.goalcost]
        
        while self.parentnode:
            self = self.parentnode
            goaltrack.append(self.goalcost)
            
        return len(goaltrack)


In [22]:
#implementation of function "Astar manhattanDistance"

import numpy as np
import time
goalstate = np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])
class AstarManhattanNode:
    def __init__(self,data,parentnode,goalcost,heur_cost):
        self.data = data
        self.parentnode = parentnode
        self.goalcost = goalcost
        self.heur_cost = heur_cost
        self.MOVEUP = None
        self.MOVELEFT = None
        self.MOVEDOWN = None
        self.MOVERIGHT = None
    
    def prob_MOVEUP(self):
        indexzero=np.where(self.data == 0)
        if indexzero[1] == 0:
            return False
        else:
            temp = self.data[indexzero[0],indexzero[1]-1]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0],indexzero[1]-1] = 0
            return newdata,True
       
    
    def prob_MOVELEFT(self):
        indexzero=np.where(self.data == 0)
        if indexzero[0] == 2:
            return False
        else:
            temp = self.data[indexzero[0]+1,indexzero[1]]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0]+1,indexzero[1]] = 0
            return newdata,True
        
        
    def prob_MOVEDOWN(self):
        indexzero=np.where(self.data == 0)
        if indexzero[1] == 2:
            return False
        else:
            temp = self.data[indexzero[0],indexzero[1]+1]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0],indexzero[1]+1] = 0
            return newdata,True
            
    def prob_MOVERIGHT(self):
        indexzero=np.where(self.data == 0)
        if indexzero[0] == 0:
            return False
        else:
            temp = self.data[indexzero[0]-1,indexzero[1]]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0]-1,indexzero[1]] = 0
            return newdata,True
        
    def manhattanDistance(self):
        
        queue = [(self,0)] 
        frontier = set([])
        goalqueue = [(0,0)]
        iter_counter = 0
        
            

        while queue:
                queue = sorted(queue, key=lambda x:x[1])
                curr_node = queue.pop(0)[0]
                goalqueue = sorted(goalqueue, key=lambda x:x[1])
                tempgoal = goalqueue.pop(0)[0]
                #print(curr_node.data)
                
                frontier.add(tuple(curr_node.data.reshape(1,9)[0]))
                iter_counter += 1

                if np.array_equal(curr_node.data,goalstate):
                    steps_count=curr_node.print_Manhattan()
                    return steps_count,iter_counter

                else:              
                    if curr_node.prob_MOVERIGHT():
                        newdata,garbage = curr_node.prob_MOVERIGHT()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp = newdata
                            goal_dictionary = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_heurcost=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_heurcost += sum(abs(a-b) for a,b in zip((i,j), goal_dictionary[temp[i,j]]))
                                        
                            total_cost = temp_heurcost + goalcost
                            curr_node.MOVERIGHT = AstarManhattanNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVERIGHT,total_cost))
                            goalqueue.append((goalcost,total_cost))

                    if curr_node.prob_MOVEDOWN():
                        newdata,garbage = curr_node.prob_MOVEDOWN()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp = newdata
                            goal_dictionary = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_heurcost=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_heurcost += sum(abs(a-b) for a,b in zip((i,j), goal_dictionary[temp[i,j]]))
                                        
                            total_cost = temp_heurcost + goalcost
                            curr_node.MOVEDOWN = AstarManhattanNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVEDOWN,total_cost))
                            goalqueue.append((goalcost,total_cost))                               

                    if curr_node.prob_MOVELEFT():
                        newdata,garbage = curr_node.prob_MOVELEFT()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp = newdata
                            goal_dictionary = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_heurcost=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_heurcost += sum(abs(a-b) for a,b in zip((i,j), goal_dictionary[temp[i,j]]))
                            
                            total_cost = temp_heurcost + goalcost 
                            curr_node.MOVELEFT = AstarManhattanNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVELEFT,total_cost))
                            goalqueue.append((goalcost,total_cost))
                                
                    if curr_node.prob_MOVEUP():
                        newdata,garbage = curr_node.prob_MOVEUP()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp = newdata
                            goal_dictionary = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_heurcost=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_heurcost += sum(abs(a-b) for a,b in zip((i,j), goal_dictionary[temp[i,j]]))
                            
                            total_cost = temp_heurcost + goalcost
                            curr_node.MOVEUP = AstarManhattanNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVEUP,total_cost))
                            goalqueue.append((goalcost,total_cost))
                                
                                
    def print_Manhattan(self):
        trackdata = [self.data]
        goaltrack = [self.goalcost]
        
        while self.parentnode:
            self = self.parentnode
            trackdata.append(self.data)
            goaltrack.append(self.goalcost)
        print (' First Scenario Solution of the Astar manhattan:')
        
        while trackdata:
            print (trackdata.pop())
            print ('to')      
        return len(goaltrack)
    
    def astarManhattan_WOprint(self):
        
        queue = [(self,0)] 
        frontier = set([])
        goalqueue = [(0,0)]
        iter_counter = 0
        
            

        while queue:
                queue = sorted(queue, key=lambda x:x[1])
                curr_node = queue.pop(0)[0]
                goalqueue = sorted(goalqueue, key=lambda x:x[1])
                tempgoal = goalqueue.pop(0)[0]
                #print(curr_node.data)
                
                frontier.add(tuple(curr_node.data.reshape(1,9)[0]))
                iter_counter += 1

                if np.array_equal(curr_node.data,goalstate):
                    steps_count=curr_node.noresult_manhattan()
                    return steps_count,iter_counter

                else:              
                    if curr_node.prob_MOVERIGHT():
                        newdata,garbage = curr_node.prob_MOVERIGHT()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp = newdata
                            goal_dictionary = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_heurcost=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_heurcost += sum(abs(a-b) for a,b in zip((i,j), goal_dictionary[temp[i,j]]))
                                        
                            total_cost = temp_heurcost + goalcost
                            curr_node.MOVERIGHT = AstarManhattanNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVERIGHT,total_cost))
                            goalqueue.append((goalcost,total_cost))

                    if curr_node.prob_MOVEDOWN():
                        newdata,garbage = curr_node.prob_MOVEDOWN()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp = newdata
                            goal_dictionary = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_heurcost=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_heurcost += sum(abs(a-b) for a,b in zip((i,j), goal_dictionary[temp[i,j]]))
                                        
                            total_cost = temp_heurcost + goalcost
                            curr_node.MOVEDOWN = AstarManhattanNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVEDOWN,total_cost))
                            goalqueue.append((goalcost,total_cost))                               

                    if curr_node.prob_MOVELEFT():
                        newdata,garbage = curr_node.prob_MOVELEFT()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp = newdata
                            goal_dictionary = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_heurcost=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_heurcost += sum(abs(a-b) for a,b in zip((i,j), goal_dictionary[temp[i,j]]))
                            
                            total_cost = temp_heurcost + goalcost 
                            curr_node.MOVELEFT = AstarManhattanNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVELEFT,total_cost))
                            goalqueue.append((goalcost,total_cost))
                                
                    if curr_node.prob_MOVEUP():
                        newdata,garbage = curr_node.prob_MOVEUP()
                        if tuple(newdata.reshape(1,9)[0]) not in frontier:
                            goalcost = tempgoal+1
                            temp = newdata
                            goal_dictionary = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_heurcost=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_heurcost += sum(abs(a-b) for a,b in zip((i,j), goal_dictionary[temp[i,j]]))
                            
                            total_cost = temp_heurcost + goalcost
                            curr_node.MOVEUP = AstarManhattanNode(data=newdata,parentnode=curr_node,goalcost=goalcost,heur_cost=temp_heurcost)
                            queue.append((curr_node.MOVEUP,total_cost))
                            goalqueue.append((goalcost,total_cost))
                                
                                
    def noresult_manhattan(self):
        goaltrack = [self.goalcost]
        
        while self.parentnode:
            self = self.parentnode
            goaltrack.append(self.goalcost)
        
        return len(goaltrack)


In [23]:
#implementation of function "BFS" 

import numpy as np
import time
goalstate = np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])
class BFSNODE:
    def __init__(self,data,parentnode,goalcost):
        self.data = data
        self.MOVEUP = None
        self.MOVELEFT = None
        self.MOVEDOWN = None
        self.MOVERIGHT = None
        self.parentnode = parentnode
        self.goalcost = goalcost
    
    def prob_MOVEUP(self):
        indexzero=np.where(self.data == 0)
        if indexzero[1] == 0:
            return False
        else:
            temp = self.data[indexzero[0],indexzero[1]-1]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0],indexzero[1]-1] = 0
            return newdata,True
       
    
    def prob_MOVELEFT(self):
        indexzero=np.where(self.data == 0)
        if indexzero[0] == 2:
            return False
        else:
            temp = self.data[indexzero[0]+1,indexzero[1]]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0]+1,indexzero[1]] = 0
            return newdata,True
        
        
    def prob_MOVEDOWN(self):
        indexzero=np.where(self.data == 0)
        if indexzero[1] == 2:
            return False
        else:
            temp = self.data[indexzero[0],indexzero[1]+1]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0],indexzero[1]+1] = 0
            return newdata,True
            
    def prob_MOVERIGHT(self):
        indexzero=np.where(self.data == 0)
        if indexzero[0] == 0:
            return False
        else:
            temp = self.data[indexzero[0]-1,indexzero[1]]
            newdata = self.data.copy()
            newdata[indexzero[0],indexzero[1]] = temp
            newdata[indexzero[0]-1,indexzero[1]] = 0
            return newdata,True
        
    def bfs(self):
    
            queue = [self] 
            frontier = set([]) 
            iter_counter = 0
            goalqueue = [0]
            while queue:

                curr_node = queue.pop(0) 
                tempgoal = goalqueue.pop(0)
                #print(curr_node.data)
                   
                frontier.add(tuple(curr_node.data.reshape(1,9)[0]))
                iter_counter += 1

                if np.array_equal(curr_node.data,goalstate):
                    steps_count = curr_node.print_BFS()
                    return steps_count,iter_counter

                else:              
                        if curr_node.prob_MOVERIGHT():
                            newdata,garbage = curr_node.prob_MOVERIGHT()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVERIGHT = BFSNODE(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.append(curr_node.MOVERIGHT)
                                goalqueue.append(goalcost)

                        if curr_node.prob_MOVEDOWN():
                            newdata,garbage = curr_node.prob_MOVEDOWN()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVEDOWN = BFSNODE(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.append(curr_node.MOVEDOWN)
                                goalqueue.append(goalcost)
                               

                        if curr_node.prob_MOVELEFT():
                            newdata,garbage = curr_node.prob_MOVELEFT()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVELEFT = BFSNODE(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.append(curr_node.MOVELEFT)
                                goalqueue.append(goalcost)
                                
                                
                        if curr_node.prob_MOVEUP():
                            newdata,garbage = curr_node.prob_MOVEUP()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVEUP = BFSNODE(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.append(curr_node.MOVEUP)
                                goalqueue.append(goalcost)
                                
                                
    def print_BFS(self):
        trackdata = [self.data]
        goaltrack = [self.goalcost]
        
        while self.parentnode:
            self = self.parentnode
            trackdata.append(self.data)
            goaltrack.append(self.goalcost)
            
        print (' First Scenario Solution of the BFS:')
        while trackdata:
            print (trackdata.pop())
            print ('to')           
        return len(goaltrack)
    
    
    def Bfs_WOprint(self):
    
            queue = [self] 
            frontier = set([]) 
            iter_counter = 0
            goalqueue = [0]
            while queue:

                curr_node = queue.pop(0) 
                tempgoal = goalqueue.pop(0)
                #print(curr_node.data)
                   
                frontier.add(tuple(curr_node.data.reshape(1,9)[0]))
                iter_counter += 1

                if np.array_equal(curr_node.data,goalstate):
                    steps_count = curr_node.noresult_BFS()
                    return steps_count,iter_counter

                else:              
                        if curr_node.prob_MOVERIGHT():
                            newdata,garbage = curr_node.prob_MOVERIGHT()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVERIGHT = BFSNODE(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.append(curr_node.MOVERIGHT)
                                goalqueue.append(goalcost)

                        if curr_node.prob_MOVEDOWN():
                            newdata,garbage = curr_node.prob_MOVEDOWN()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVEDOWN = BFSNODE(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.append(curr_node.MOVEDOWN)
                                goalqueue.append(goalcost)
                               

                        if curr_node.prob_MOVELEFT():
                            newdata,garbage = curr_node.prob_MOVELEFT()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVELEFT = BFSNODE(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.append(curr_node.MOVELEFT)
                                goalqueue.append(goalcost)
                                
                                
                        if curr_node.prob_MOVEUP():
                            newdata,garbage = curr_node.prob_MOVEUP()
                    
                            if tuple(newdata.reshape(1,9)[0]) not in frontier:
                                goalcost = tempgoal+1
                                curr_node.MOVEUP = BFSNODE(data=newdata,parentnode=curr_node,goalcost=goalcost)
                                queue.append(curr_node.MOVEUP)
                                goalqueue.append(goalcost)
                                
                                
    def noresult_BFS(self):
        goaltrack = [self.goalcost]
        
        while self.parentnode:
            self = self.parentnode
            goaltrack.append(self.goalcost)
                  
        return len(goaltrack)


In [24]:
#implementation of function "print_result(result)"

def print_result():
    #for Iterative_deepening_DFS
    file = open("Input8PuzzleCasesUpdates.txt")
    inputstate=[]
    index=0
    for line in file:
        string=line.strip("\n").split(",")
        inputstate.append([])
        for j in range (len(string)):
            inputstate[index].append(int(string[j]))
        index+=1

    time_DFS = []
    steps_countDFS=[]
    itercount_DFS = []

    testcase = np.array(inputstate.pop(0)).reshape((3,3))
    root=NODEDFS(data=testcase,parentnode=None,goalcost=0)

    starttime = time.time()
        #------------------------function call----------------------------
    steps_count,iter_counter = root.IterativeDFS()
    time_DFS.append(time.time()-starttime)
    steps_countDFS.append(steps_count)
    itercount_DFS.append(iter_counter)

    for i in range(99):

        testcase = np.array(inputstate.pop(0)).reshape((3,3))
        root=NODEDFS(data=testcase,parentnode=None,goalcost=0)

        starttime = time.time()
        steps_count,iter_counter = root.iterdeepDFS_WOprint()
        time_DFS.append(time.time()-starttime)
        steps_countDFS.append(steps_count)
        itercount_DFS.append(iter_counter)
        
    #FOR ASTAR_MISPLACED
    file = open("Input8PuzzleCasesUpdates.txt")
    inputstate=[]
    index=0
    for line in file:
        string=line.strip("\n").split(",")
        inputstate.append([])
        for j in range (len(string)):
            inputstate[index].append(int(string[j]))
        index+=1

    time_AMIS = []
    stepscount_AMIS=[]
    itercount_AMIS = []

    testcase = np.array(inputstate.pop(0)).reshape((3,3))
    root=AstarMisplacedNode(data=testcase,parentnode=None,goalcost=0,heur_cost=0)

    starttime = time.time()
    #------------------------function call----------------------------
    steps_count,iter_counter = root.aStarMisplaced()
    time_AMIS.append(time.time()-starttime)
    stepscount_AMIS.append(steps_count)
    itercount_AMIS.append(iter_counter)

    for i in range(99):

        testcase = np.array(inputstate.pop(0)).reshape((3,3))
        root=AstarMisplacedNode(data=testcase,parentnode=None,goalcost=0,heur_cost=0)

        starttime = time.time()
        #---------------
        steps_count,iter_counter = root.astarMisplaced_WOprint()
        time_AMIS.append(time.time()-starttime)
        stepscount_AMIS.append(steps_count)
        itercount_AMIS.append(iter_counter)
        
    # FOR ASTAR_MANHATTAN
    file = open("Input8PuzzleCasesUpdates.txt")
    inputstate=[]
    index=0
    for line in file:
        string=line.strip("\n").split(",")
        inputstate.append([])
        for j in range (len(string)):
            inputstate[index].append(int(string[j]))
        index+=1

    time_AMAN = []
    stepscount_AMAN=[]
    itercount_AMAN = []

    testcase = np.array(inputstate.pop(0)).reshape((3,3))
    root=AstarManhattanNode(data=testcase,parentnode=None,goalcost=0,heur_cost=0)

    starttime = time.time()
        #------------------------function call----------------------------
    steps_count,iter_counter = root.manhattanDistance()
    time_AMAN.append(time.time()-starttime)
    stepscount_AMAN.append(steps_count)
    itercount_AMAN.append(iter_counter)

    for i in range(99):

        testcase = np.array(inputstate.pop(0)).reshape((3,3))
        root=AstarManhattanNode(data=testcase,parentnode=None,goalcost=0,heur_cost=0)

        starttime = time.time()
        #--------------
        steps_count,iter_counter = root.astarManhattan_WOprint()
        time_AMAN.append(time.time()-starttime)
        stepscount_AMAN.append(steps_count)
        itercount_AMAN.append(iter_counter)
        
    # FOR BFS
    file = open("Input8PuzzleCasesUpdates.txt")
    inputstate=[]
    index=0
    for line in file:
        string=line.strip("\n").split(",")
        inputstate.append([])
        for j in range (len(string)):
            inputstate[index].append(int(string[j]))
        index+=1

    time_BFS = []
    stepscount_BFS=[]
    itercount_BFS = []

    testcase = np.array(inputstate.pop(0)).reshape((3,3))
    root=BFSNODE(data=testcase,parentnode=None,goalcost=0)

    starttime = time.time()
        #------------------------function call----------------------------
    steps_count,iter_counter = root.bfs()
    time_BFS.append(time.time()-starttime)
    stepscount_BFS.append(steps_count)
    itercount_BFS.append(iter_counter)

    for i in range(19):

        testcase = np.array(inputstate.pop(0)).reshape((3,3))
        root=BFSNODE(data=testcase,parentnode=None,goalcost=0)

        starttime = time.time()
        #-------------
        steps_count,iter_counter = root.Bfs_WOprint()
        time_BFS.append(time.time()-starttime)
        stepscount_BFS.append(steps_count)
        itercount_BFS.append(iter_counter)
        
        
        
    print('\t\t\t\t Average_Steps_count \t Average_Time \t Average_Iterations')
    print('\t Iterative DFS \t\t\t ', sum(steps_countDFS)/100, ' \t ', sum(time_DFS)/100, ' \t ', sum(itercount_DFS)/100)
    print('\t A*(Misplaced) \t\t\t ', sum(stepscount_AMIS)/100, ' \t ', sum(time_AMIS)/100, ' \t ', sum(itercount_AMIS)/100)
    print('\t A*(Manhattan) \t\t\t ', sum(stepscount_AMAN)/100, ' \t ', sum(time_AMAN)/100, ' \t ', sum(itercount_AMAN)/100)
    print('\t BFS \t\t\t\t ', sum(stepscount_BFS)/20, ' \t ', sum(time_BFS)/20, ' \t ', sum(itercount_BFS)/20)
    
    return steps_countDFS,time_DFS,itercount_DFS,stepscount_AMIS,time_AMIS,itercount_AMIS,stepscount_AMAN,time_AMAN,itercount_AMAN,stepscount_BFS,time_BFS,itercount_BFS


In [25]:
#you need to implement print_result function to print out the result according to the required format
steps_countDFS,time_DFS,itercount_DFS,stepscount_AMIS,time_AMIS,itercount_AMIS,stepscount_AMAN,time_AMAN,itercount_AMAN,stepscount_BFS,time_BFS,itercount_BFS=print_result()


First Scenario Solution of the IterativeDFS:
[[8 7 5]
 [4 1 2]
 [3 0 6]]
to
[[8 7 5]
 [4 1 2]
 [0 3 6]]
to
[[8 7 5]
 [0 1 2]
 [4 3 6]]
to
[[8 7 5]
 [1 0 2]
 [4 3 6]]
to
[[8 7 5]
 [1 3 2]
 [4 0 6]]
to
[[8 7 5]
 [1 3 2]
 [0 4 6]]
to
[[8 7 5]
 [0 3 2]
 [1 4 6]]
to
[[8 7 5]
 [3 0 2]
 [1 4 6]]
to
[[8 0 5]
 [3 7 2]
 [1 4 6]]
to
[[0 8 5]
 [3 7 2]
 [1 4 6]]
to
[[3 8 5]
 [0 7 2]
 [1 4 6]]
to
[[3 8 5]
 [1 7 2]
 [0 4 6]]
to
[[3 8 5]
 [1 7 2]
 [4 0 6]]
to
[[3 8 5]
 [1 7 2]
 [4 6 0]]
to
[[3 8 5]
 [1 7 0]
 [4 6 2]]
to
[[3 8 5]
 [1 0 7]
 [4 6 2]]
to
[[3 0 5]
 [1 8 7]
 [4 6 2]]
to
[[0 3 5]
 [1 8 7]
 [4 6 2]]
to
[[1 3 5]
 [0 8 7]
 [4 6 2]]
to
[[1 3 5]
 [4 8 7]
 [0 6 2]]
to
[[1 3 5]
 [4 8 7]
 [6 0 2]]
to
[[1 3 5]
 [4 8 7]
 [6 2 0]]
to
[[1 3 5]
 [4 8 0]
 [6 2 7]]
to
[[1 3 5]
 [4 0 8]
 [6 2 7]]
to
[[1 3 5]
 [4 2 8]
 [6 0 7]]
to
[[1 3 5]
 [4 2 8]
 [0 6 7]]
to
[[1 3 5]
 [0 2 8]
 [4 6 7]]
to
[[0 3 5]
 [1 2 8]
 [4 6 7]]
to
[[3 0 5]
 [1 2 8]
 [4 6 7]]
to
[[3 2 5]
 [1 0 8]
 [4 6 7]]
to
[[3 2 5]
 [0 1 8]
 [4 6 7

In [26]:

'''
You can insert as many cells as you want above
You are not Allowed to modify the code below this line.
#you need to implement print_result function to print out the result according to the required format
print_result(result)
'''


'\nYou can insert as many cells as you want above\nYou are not Allowed to modify the code below this line.\n#you need to implement print_result function to print out the result according to the required format\nprint_result(result)\n'

In [27]:

'''
The output format should be as follows. You only need to give one sample solution as an example.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Solution of the first Scenario:
X X X
X X X
X X X
to
X X X
X X X
X X X
to
X X X
X X X
X X X
to
X X X
X X X
X X X
to
.
.
.
0 1 2
3 4 5
6 7 8

                Average_Steps_count    Average_Time   Average_Iterations   
UCS
A*(Misplaced)
A*(Manhattan)
BFS



'''

'\nThe output format should be as follows. You only need to give one sample solution as an example.\n+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nSolution of the first Scenario:\nX X X\nX X X\nX X X\nto\nX X X\nX X X\nX X X\nto\nX X X\nX X X\nX X X\nto\nX X X\nX X X\nX X X\nto\n.\n.\n.\n0 1 2\n3 4 5\n6 7 8\n\n                Average_Steps_count    Average_Time   Average_Iterations   \nUCS\nA*(Misplaced)\nA*(Manhattan)\nBFS\n\n\n\n'